name: 'Cache packages'
description: 'get or set cache packages'

runs:
  using: composite
  steps:
    - name: Cache Packages
      id: cache-packages
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ./packages/
        key: pkg-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.run_id }}-${{ github.sha }}
