name: 'Cache packages'
description: 'get or set cache packages'

runs:
  using: composite
  steps:
    - name: Cache Packages
      id: cache-packages
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ./packages/
        key: pkg-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.run_id }}-${{ github.sha }}
