name: 'Cache packages'
description: 'get or set cache packages'

runs:
  using: composite
  steps:
    - name: Cache Packages
      id: cache-packages
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ./packages/
        key: pkg-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.run_id }}-${{ github.sha }}
