name: 'Cache packages'
description: 'get or set cache packages'

runs:
  using: composite
  steps:
    - name: Cache Packages
      id: cache-packages
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ./packages/
        key: pkg-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.run_id }}-${{ github.sha }}
