version: '3.9'

services:
  nginx:
    build: ./nginx
    container_name: reverse_proxy
    ports:
      - '80:80'
    depends_on:
      - verdaccio
    volumes:
      - logs:/var/log/nginx
    restart: unless-stopped

  verdaccio:
    image: verdaccio/verdaccio:nightly-master
    container_name: verdaccio_root_path
    ports:
      - '4873:4873'
    volumes:
      - verdaccio:/verdaccio
    restart: unless-stopped

volumes:
  verdaccio:
  logs:
