defaultSemverRangePrefix: ""

enableScripts: false

nodeLinker: node-modules

enableGlobalCache: false

npmMinimalAgeGate: '15d'

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.15.0.cjs

npmPreapprovedPackages:
  - '@verdaccio/*'
  - 'verdaccio-*'
