compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - ./yarn-plugins/plugin-postinstall.js

yarnPath: .yarn/releases/yarn-4.9.2.cjs
