approvedGitRepositories:
  - "**"

defaultSemverRangePrefix: ""

enableScripts: true

nodeLinker: node-modules

enableGlobalCache: false

npmMinimalAgeGate: '15d'

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.14.1.cjs

npmMinimalAgeGate: 4320
npmPreapprovedPackages:
  - '@verdaccio/*'
  - 'verdaccio-*'
