codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '80...85'

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'diff,flags,tree'
  behavior: default
  require_changes: no
