project_id: 295539
api_token_env: CROWDIN_VERDACCIO_API_KEY
# token local testing
# api_token: token_secret

preserve_hierarchy: true

files:
  - source: /packages/core/i18n/src/crowdin/*.json
    translation: '/packages/core/i18n/src/download_translations/%locale%/%original_file_name%'
  - source: /packages/plugins/ui-theme/src/i18n/crowdin/*.json
    translation: '/packages/plugins/ui-theme/src/i18n/download_translations/%locale%/%original_file_name%'
