project_id: 295539
api_token_env: CROWDIN_VERDACCIO_API_KEY
# token local testing
# api_token: token_secret

preserve_hierarchy: true

files:
  - source: /packages/plugins/ui-theme/src/i18n/crowdin/*.json
    translation: '/packages/plugins/ui-theme/src/i18n/download_translations/%locale%/%original_file_name%'
  - source: /website/i18n/en/**/*
    translation: '/website/i18n/%locale%/**/%original_file_name%'
  - source: /website/docs/**/*
    translation: '/website/i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%'
    ignore: [/website/docs/api/**/*]
  - source: /website/versioned_docs/**/*
    translation: /website/i18n/%locale%/docusaurus-plugin-content-docs/**/%original_file_name%
    ignore: [/website/versioned_docs/version-5.x/api/**/*, /website/versioned_docs/version-6.x/api/**/*]
   