FROM hypriot/rpi-node:6-onbuild

RUN mkdir -p /verdaccio/storage /verdaccio/conf

WORKDIR /verdaccio

ADD conf/docker.yaml /verdaccio/conf/config.yaml

ENV VERDACCIO_PORT 4873
ENV VERDACCIO_PROTOCOL http

EXPOSE $VERDACCIO_PORT

VOLUME ["/verdaccio/conf", "/verdaccio/storage"]

CMD ["/usr/src/app/bin/verdaccio", "--config", "/verdaccio/conf/config.yaml", "--listen", "0.0.0.0:$VERDACCIO_PORT"]
