# use "yapm install ." if you're installing this from git repository

name: sinopia
version: 0.11.0
description: Private npm repository server

author:
  name: Alex Kocharin
  email: alex@kocharin.ru

repository:
  type: git
  url: git://github.com/rlidwka/sinopia

main: index.js

bin:
  sinopia: ./bin/sinopia

dependencies:
  express: '>=3.15.0 <4.0.0-0'

  commander: '>=2.3.0 <3.0.0-0'
  js-yaml: '>=3.0.1 <4.0.0-0'
  cookies: '>=0.5.0 <1.0.0-0'
  request: '>=2.31.0 <3.0.0-0'
  async: '>=0.9.0 <1.0.0-0'

  # 2.x and 3.x have the same interface
  semver: '>=2.2.1 <4.0.0-0'

  minimatch: '>=0.2.14 <2.0.0-0'
  bunyan: '>=0.22.1 <2.0.0-0'
  handlebars: '1.x'
  highlight.js: '8.x'
  lunr: '>=0.5.2 <1.0.0-0'
  marked: '>=0.3.2 <1.0.0-0'

  # bundled deps, see below
  mkdirp: '>=0.3.5 <1.0.0-0'
  unopinionate: '>=0.0.4 <1.0.0-0'
  onclick: '>=0.1.0 <1.0.0-0'
  onscroll: '>=0.0.3 <1.0.0-0'
  transition-complete: '>=0.0.2 <1.0.0-0'
  helpers.less: 'git://github.com/bpeacock/helpers.less.git'
  sinopia-htpasswd: '>= 0.2.0'
  http-errors: '~1.2.0' # ferver

  # TODO: not really needed
  tar.gz: '~0.1.1'

optionalDependencies:
  # those are native modules that could fail to compile
  # and unavailable on windows
  fs-ext: '>=0.3.2 <1.0.0-0'
  crypt3: 'git://github.com/sendanor/node-crypt3.git' # for sinopia-htpasswd

# Policy for now:
# - small, unstable and rarely updated libraries (i.e. crypt3) get bundled
# - big, stable and frequently updated libraries (i.e. request) don't
#
# When sinopia@1.0.0 gets out, all deps will probably be
# bundled to increase stability and reduce install time.
bundledDependencies:
  - mkdirp
  - unopinionate
  - onclick
  - onscroll
  - transition-complete
  - helpers.less
  - tar.gz
  - sinopia-htpasswd
  - http-errors

devDependencies:
  rimraf: '>=2.2.5 <3.0.0-0'
  mocha: '>=1.17.0 <2.0.0-0'

  # linting tools
  eslint: '~0.6.0'

  # for debugging memory leaks, it'll be require()'d if
  # installed, but I don't want it to be installed everytime
  #heapdump: '*'

  browserify: '>=3.46.0 <4.0.0-0'
  browserify-handlebars: '~0.2.0'
  grunt: '>=0.4.4 <1.0.0-0'
  grunt-browserify: '>=2.0.8 <3.0.0-0'
  grunt-contrib-less: '>=0.11.0 <1.0.0-0'
  grunt-contrib-watch: '>=0.6.1 <1.0.0-0'

keywords:
  - private
  - package
  - repository
  - registry
  - modules
  - proxy
  - server

scripts:
  test: mocha -R dot ./test/functional ./test/unit
  test-travis: mocha -R spec ./test/functional ./test/unit
  lint: eslint -c ./.eslint.yaml ./lib
  prepublish: js-yaml package.yaml > package.json

# we depend on streams2 stuff
# it can be replaced with isaacs/readable-stream, ask if you need to use 0.8
engines:
  node: '>=0.10'

preferGlobal: true

publishConfig:
  registry: https://registry.npmjs.org/

license:
  type: WTFPL
  url: http://www.wtfpl.net/txt/copying/
