allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@verdaccio/*'
  - '@verdaccio-scope/*'
  - 'verdaccio-*'
ignoreScripts: true
saveExact: true
preferFrozenLockfile: true
