module.exports = {
  endOfLine: 'lf',
  useTabs: false,
  printWidth: 180,
  tabWidth: 2,
  singleQuote: true,
  bracketSpacing: true,
  trailingComma: 'es5',
  semi: true,
  plugins: [require('@trivago/prettier-plugin-sort-imports')],
  importOrder: ['^@verdaccio/(.*)$', '^[./]'],
  importOrderSeparation: true,
  importOrderParserPlugins: ['typescript', 'classProperties', 'jsx'],
  importOrderSortSpecifiers: true,
};
