// flow-typed signature: b7109b7e394ff03ed211118d5af4cff8
// flow-typed version: <<STUB>>/asciidoctor.js_v1.5.6/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'asciidoctor.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'asciidoctor.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'asciidoctor.js/dist/asciidoctor' {
  declare module.exports: any;
}

declare module 'asciidoctor.js/dist/asciidoctor.min' {
  declare module.exports: any;
}

declare module 'asciidoctor.js/dist/browser/asciidoctor' {
  declare module.exports: any;
}

declare module 'asciidoctor.js/dist/nashorn/asciidoctor' {
  declare module.exports: any;
}

declare module 'asciidoctor.js/dist/node/asciidoctor' {
  declare module.exports: any;
}

declare module 'asciidoctor.js/dist/umd/asciidoctor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'asciidoctor.js/dist/asciidoctor.js' {
  declare module.exports: $Exports<'asciidoctor.js/dist/asciidoctor'>;
}
declare module 'asciidoctor.js/dist/asciidoctor.min.js' {
  declare module.exports: $Exports<'asciidoctor.js/dist/asciidoctor.min'>;
}
declare module 'asciidoctor.js/dist/browser/asciidoctor.js' {
  declare module.exports: $Exports<'asciidoctor.js/dist/browser/asciidoctor'>;
}
declare module 'asciidoctor.js/dist/nashorn/asciidoctor.js' {
  declare module.exports: $Exports<'asciidoctor.js/dist/nashorn/asciidoctor'>;
}
declare module 'asciidoctor.js/dist/node/asciidoctor.js' {
  declare module.exports: $Exports<'asciidoctor.js/dist/node/asciidoctor'>;
}
declare module 'asciidoctor.js/dist/umd/asciidoctor.js' {
  declare module.exports: $Exports<'asciidoctor.js/dist/umd/asciidoctor'>;
}
