// flow-typed signature: d369e8a6411b1ce4fcd5339b6d41e441
// flow-typed version: <<STUB>>/cors_v2.8.4/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cors/lib/index' {
  declare module.exports: any;
}

declare module 'cors/test/basic-auth' {
  declare module.exports: any;
}

declare module 'cors/test/body-events' {
  declare module.exports: any;
}

declare module 'cors/test/cors' {
  declare module.exports: any;
}

declare module 'cors/test/error-response' {
  declare module.exports: any;
}

declare module 'cors/test/example-app' {
  declare module.exports: any;
}

declare module 'cors/test/issue-2' {
  declare module.exports: any;
}

declare module 'cors/test/issue-31' {
  declare module.exports: any;
}

declare module 'cors/test/support/env' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cors/lib/index.js' {
  declare module.exports: $Exports<'cors/lib/index'>;
}
declare module 'cors/test/basic-auth.js' {
  declare module.exports: $Exports<'cors/test/basic-auth'>;
}
declare module 'cors/test/body-events.js' {
  declare module.exports: $Exports<'cors/test/body-events'>;
}
declare module 'cors/test/cors.js' {
  declare module.exports: $Exports<'cors/test/cors'>;
}
declare module 'cors/test/error-response.js' {
  declare module.exports: $Exports<'cors/test/error-response'>;
}
declare module 'cors/test/example-app.js' {
  declare module.exports: $Exports<'cors/test/example-app'>;
}
declare module 'cors/test/issue-2.js' {
  declare module.exports: $Exports<'cors/test/issue-2'>;
}
declare module 'cors/test/issue-31.js' {
  declare module.exports: $Exports<'cors/test/issue-31'>;
}
declare module 'cors/test/support/env.js' {
  declare module.exports: $Exports<'cors/test/support/env'>;
}
