// flow-typed signature: 10998829754884cf0b6f5fe169611a08
// flow-typed version: <<STUB>>/js-yaml_v3.10.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-yaml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-yaml/bin/js-yaml' {
  declare module.exports: any;
}

declare module 'js-yaml/dist/js-yaml' {
  declare module.exports: any;
}

declare module 'js-yaml/dist/js-yaml.min' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/common' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/dumper' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/exception' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/loader' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/mark' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/schema' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/schema/core' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/schema/default_full' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/schema/default_safe' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/schema/failsafe' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/schema/json' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/binary' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/bool' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/float' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/int' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/js/function' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/js/regexp' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/js/undefined' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/map' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/merge' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/null' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/omap' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/pairs' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/seq' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/set' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/str' {
  declare module.exports: any;
}

declare module 'js-yaml/lib/js-yaml/type/timestamp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-yaml/bin/js-yaml.js' {
  declare module.exports: $Exports<'js-yaml/bin/js-yaml'>;
}
declare module 'js-yaml/dist/js-yaml.js' {
  declare module.exports: $Exports<'js-yaml/dist/js-yaml'>;
}
declare module 'js-yaml/dist/js-yaml.min.js' {
  declare module.exports: $Exports<'js-yaml/dist/js-yaml.min'>;
}
declare module 'js-yaml/index' {
  declare module.exports: $Exports<'js-yaml'>;
}
declare module 'js-yaml/index.js' {
  declare module.exports: $Exports<'js-yaml'>;
}
declare module 'js-yaml/lib/js-yaml.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml'>;
}
declare module 'js-yaml/lib/js-yaml/common.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/common'>;
}
declare module 'js-yaml/lib/js-yaml/dumper.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/dumper'>;
}
declare module 'js-yaml/lib/js-yaml/exception.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/exception'>;
}
declare module 'js-yaml/lib/js-yaml/loader.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/loader'>;
}
declare module 'js-yaml/lib/js-yaml/mark.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/mark'>;
}
declare module 'js-yaml/lib/js-yaml/schema.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/schema'>;
}
declare module 'js-yaml/lib/js-yaml/schema/core.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/schema/core'>;
}
declare module 'js-yaml/lib/js-yaml/schema/default_full.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/schema/default_full'>;
}
declare module 'js-yaml/lib/js-yaml/schema/default_safe.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/schema/default_safe'>;
}
declare module 'js-yaml/lib/js-yaml/schema/failsafe.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/schema/failsafe'>;
}
declare module 'js-yaml/lib/js-yaml/schema/json.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/schema/json'>;
}
declare module 'js-yaml/lib/js-yaml/type.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type'>;
}
declare module 'js-yaml/lib/js-yaml/type/binary.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/binary'>;
}
declare module 'js-yaml/lib/js-yaml/type/bool.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/bool'>;
}
declare module 'js-yaml/lib/js-yaml/type/float.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/float'>;
}
declare module 'js-yaml/lib/js-yaml/type/int.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/int'>;
}
declare module 'js-yaml/lib/js-yaml/type/js/function.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/js/function'>;
}
declare module 'js-yaml/lib/js-yaml/type/js/regexp.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/js/regexp'>;
}
declare module 'js-yaml/lib/js-yaml/type/js/undefined.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/js/undefined'>;
}
declare module 'js-yaml/lib/js-yaml/type/map.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/map'>;
}
declare module 'js-yaml/lib/js-yaml/type/merge.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/merge'>;
}
declare module 'js-yaml/lib/js-yaml/type/null.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/null'>;
}
declare module 'js-yaml/lib/js-yaml/type/omap.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/omap'>;
}
declare module 'js-yaml/lib/js-yaml/type/pairs.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/pairs'>;
}
declare module 'js-yaml/lib/js-yaml/type/seq.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/seq'>;
}
declare module 'js-yaml/lib/js-yaml/type/set.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/set'>;
}
declare module 'js-yaml/lib/js-yaml/type/str.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/str'>;
}
declare module 'js-yaml/lib/js-yaml/type/timestamp.js' {
  declare module.exports: $Exports<'js-yaml/lib/js-yaml/type/timestamp'>;
}
