// flow-typed signature: 12a8262920099086254f18882b49d862
// flow-typed version: <<STUB>>/JSONStream_v1.3.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'JSONStream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'JSONStream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'JSONStream/bin' {
  declare module.exports: any;
}

declare module 'JSONStream/examples/all_docs' {
  declare module.exports: any;
}

declare module 'JSONStream/test/bool' {
  declare module.exports: any;
}

declare module 'JSONStream/test/browser' {
  declare module.exports: any;
}

declare module 'JSONStream/test/destroy_missing' {
  declare module.exports: any;
}

declare module 'JSONStream/test/disabled/doubledot1' {
  declare module.exports: any;
}

declare module 'JSONStream/test/disabled/doubledot2' {
  declare module.exports: any;
}

declare module 'JSONStream/test/empty' {
  declare module.exports: any;
}

declare module 'JSONStream/test/error_contents' {
  declare module.exports: any;
}

declare module 'JSONStream/test/fn' {
  declare module.exports: any;
}

declare module 'JSONStream/test/gen' {
  declare module.exports: any;
}

declare module 'JSONStream/test/header_footer' {
  declare module.exports: any;
}

declare module 'JSONStream/test/issues' {
  declare module.exports: any;
}

declare module 'JSONStream/test/keys' {
  declare module.exports: any;
}

declare module 'JSONStream/test/map' {
  declare module.exports: any;
}

declare module 'JSONStream/test/multiple_objects_error' {
  declare module.exports: any;
}

declare module 'JSONStream/test/multiple_objects' {
  declare module.exports: any;
}

declare module 'JSONStream/test/null' {
  declare module.exports: any;
}

declare module 'JSONStream/test/parsejson' {
  declare module.exports: any;
}

declare module 'JSONStream/test/stringify_object' {
  declare module.exports: any;
}

declare module 'JSONStream/test/stringify' {
  declare module.exports: any;
}

declare module 'JSONStream/test/test' {
  declare module.exports: any;
}

declare module 'JSONStream/test/test2' {
  declare module.exports: any;
}

declare module 'JSONStream/test/two-ways' {
  declare module.exports: any;
}

// Filename aliases
declare module 'JSONStream/bin.js' {
  declare module.exports: $Exports<'JSONStream/bin'>;
}
declare module 'JSONStream/examples/all_docs.js' {
  declare module.exports: $Exports<'JSONStream/examples/all_docs'>;
}
declare module 'JSONStream/index' {
  declare module.exports: $Exports<'JSONStream'>;
}
declare module 'JSONStream/index.js' {
  declare module.exports: $Exports<'JSONStream'>;
}
declare module 'JSONStream/test/bool.js' {
  declare module.exports: $Exports<'JSONStream/test/bool'>;
}
declare module 'JSONStream/test/browser.js' {
  declare module.exports: $Exports<'JSONStream/test/browser'>;
}
declare module 'JSONStream/test/destroy_missing.js' {
  declare module.exports: $Exports<'JSONStream/test/destroy_missing'>;
}
declare module 'JSONStream/test/disabled/doubledot1.js' {
  declare module.exports: $Exports<'JSONStream/test/disabled/doubledot1'>;
}
declare module 'JSONStream/test/disabled/doubledot2.js' {
  declare module.exports: $Exports<'JSONStream/test/disabled/doubledot2'>;
}
declare module 'JSONStream/test/empty.js' {
  declare module.exports: $Exports<'JSONStream/test/empty'>;
}
declare module 'JSONStream/test/error_contents.js' {
  declare module.exports: $Exports<'JSONStream/test/error_contents'>;
}
declare module 'JSONStream/test/fn.js' {
  declare module.exports: $Exports<'JSONStream/test/fn'>;
}
declare module 'JSONStream/test/gen.js' {
  declare module.exports: $Exports<'JSONStream/test/gen'>;
}
declare module 'JSONStream/test/header_footer.js' {
  declare module.exports: $Exports<'JSONStream/test/header_footer'>;
}
declare module 'JSONStream/test/issues.js' {
  declare module.exports: $Exports<'JSONStream/test/issues'>;
}
declare module 'JSONStream/test/keys.js' {
  declare module.exports: $Exports<'JSONStream/test/keys'>;
}
declare module 'JSONStream/test/map.js' {
  declare module.exports: $Exports<'JSONStream/test/map'>;
}
declare module 'JSONStream/test/multiple_objects_error.js' {
  declare module.exports: $Exports<'JSONStream/test/multiple_objects_error'>;
}
declare module 'JSONStream/test/multiple_objects.js' {
  declare module.exports: $Exports<'JSONStream/test/multiple_objects'>;
}
declare module 'JSONStream/test/null.js' {
  declare module.exports: $Exports<'JSONStream/test/null'>;
}
declare module 'JSONStream/test/parsejson.js' {
  declare module.exports: $Exports<'JSONStream/test/parsejson'>;
}
declare module 'JSONStream/test/stringify_object.js' {
  declare module.exports: $Exports<'JSONStream/test/stringify_object'>;
}
declare module 'JSONStream/test/stringify.js' {
  declare module.exports: $Exports<'JSONStream/test/stringify'>;
}
declare module 'JSONStream/test/test.js' {
  declare module.exports: $Exports<'JSONStream/test/test'>;
}
declare module 'JSONStream/test/test2.js' {
  declare module.exports: $Exports<'JSONStream/test/test2'>;
}
declare module 'JSONStream/test/two-ways.js' {
  declare module.exports: $Exports<'JSONStream/test/two-ways'>;
}
