// flow-typed signature: f588bf5982dc1140e97108be62b860db
// flow-typed version: <<STUB>>/lunr-mutable-indexes_v2.3.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lunr-mutable-indexes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lunr-mutable-indexes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lunr-mutable-indexes/lib/lunr_mutable' {
  declare module.exports: any;
}

declare module 'lunr-mutable-indexes/lib/mutable_builder' {
  declare module.exports: any;
}

declare module 'lunr-mutable-indexes/lib/mutable_index' {
  declare module.exports: any;
}

declare module 'lunr-mutable-indexes/lunr-mutable' {
  declare module.exports: any;
}

declare module 'lunr-mutable-indexes/test/mutable_serialization_test' {
  declare module.exports: any;
}

declare module 'lunr-mutable-indexes/test/mutable_sugar_test' {
  declare module.exports: any;
}

declare module 'lunr-mutable-indexes/test/mutable_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lunr-mutable-indexes/lib/lunr_mutable.js' {
  declare module.exports: $Exports<'lunr-mutable-indexes/lib/lunr_mutable'>;
}
declare module 'lunr-mutable-indexes/lib/mutable_builder.js' {
  declare module.exports: $Exports<'lunr-mutable-indexes/lib/mutable_builder'>;
}
declare module 'lunr-mutable-indexes/lib/mutable_index.js' {
  declare module.exports: $Exports<'lunr-mutable-indexes/lib/mutable_index'>;
}
declare module 'lunr-mutable-indexes/lunr-mutable.js' {
  declare module.exports: $Exports<'lunr-mutable-indexes/lunr-mutable'>;
}
declare module 'lunr-mutable-indexes/test/mutable_serialization_test.js' {
  declare module.exports: $Exports<'lunr-mutable-indexes/test/mutable_serialization_test'>;
}
declare module 'lunr-mutable-indexes/test/mutable_sugar_test.js' {
  declare module.exports: $Exports<'lunr-mutable-indexes/test/mutable_sugar_test'>;
}
declare module 'lunr-mutable-indexes/test/mutable_test.js' {
  declare module.exports: $Exports<'lunr-mutable-indexes/test/mutable_test'>;
}
