// flow-typed signature: 56b4e33a3df0ef57946fd42834d344b8
// flow-typed version: <<STUB>>/mime_v2.2.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mime/cli' {
  declare module.exports: any;
}

declare module 'mime/lite' {
  declare module.exports: any;
}

declare module 'mime/Mime' {
  declare module.exports: any;
}

declare module 'mime/src/build' {
  declare module.exports: any;
}

declare module 'mime/src/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mime/cli.js' {
  declare module.exports: $Exports<'mime/cli'>;
}
declare module 'mime/index' {
  declare module.exports: $Exports<'mime'>;
}
declare module 'mime/index.js' {
  declare module.exports: $Exports<'mime'>;
}
declare module 'mime/lite.js' {
  declare module.exports: $Exports<'mime/lite'>;
}
declare module 'mime/Mime.js' {
  declare module.exports: $Exports<'mime/Mime'>;
}
declare module 'mime/src/build.js' {
  declare module.exports: $Exports<'mime/src/build'>;
}
declare module 'mime/src/test.js' {
  declare module.exports: $Exports<'mime/src/test'>;
}
