// flow-typed signature: 0c37b93b28df38b46c7edb9bc9d278ad
// flow-typed version: <<STUB>>/node-mocks-http_v1.6.7/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-mocks-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-mocks-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-mocks-http/lib/express/mock-application' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/express/mock-express' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/express/mock-request' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/express/utils/define-getter' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/http-mock' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/mockEventEmitter' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/mockRequest' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/mockResponse' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/mockWritableStream' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/node/_http_incoming' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/node/_http_server' {
  declare module.exports: any;
}

declare module 'node-mocks-http/lib/node/http' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-mocks-http/lib/express/mock-application.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/express/mock-application'>;
}
declare module 'node-mocks-http/lib/express/mock-express.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/express/mock-express'>;
}
declare module 'node-mocks-http/lib/express/mock-request.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/express/mock-request'>;
}
declare module 'node-mocks-http/lib/express/utils/define-getter.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/express/utils/define-getter'>;
}
declare module 'node-mocks-http/lib/http-mock.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/http-mock'>;
}
declare module 'node-mocks-http/lib/mockEventEmitter.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/mockEventEmitter'>;
}
declare module 'node-mocks-http/lib/mockRequest.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/mockRequest'>;
}
declare module 'node-mocks-http/lib/mockResponse.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/mockResponse'>;
}
declare module 'node-mocks-http/lib/mockWritableStream.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/mockWritableStream'>;
}
declare module 'node-mocks-http/lib/node/_http_incoming.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/node/_http_incoming'>;
}
declare module 'node-mocks-http/lib/node/_http_server.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/node/_http_server'>;
}
declare module 'node-mocks-http/lib/node/http.js' {
  declare module.exports: $Exports<'node-mocks-http/lib/node/http'>;
}
