// flow-typed signature: 5ea2cb6aa83979de9573ab3e3723be3f
// flow-typed version: <<STUB>>/pkginfo_v0.4.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pkginfo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pkginfo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pkginfo/examples/all-properties' {
  declare module.exports: any;
}

declare module 'pkginfo/examples/array-argument' {
  declare module.exports: any;
}

declare module 'pkginfo/examples/multiple-properties' {
  declare module.exports: any;
}

declare module 'pkginfo/examples/object-argument' {
  declare module.exports: any;
}

declare module 'pkginfo/examples/single-property' {
  declare module.exports: any;
}

declare module 'pkginfo/examples/target-dir' {
  declare module.exports: any;
}

declare module 'pkginfo/lib/pkginfo' {
  declare module.exports: any;
}

declare module 'pkginfo/test/pkginfo-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pkginfo/examples/all-properties.js' {
  declare module.exports: $Exports<'pkginfo/examples/all-properties'>;
}
declare module 'pkginfo/examples/array-argument.js' {
  declare module.exports: $Exports<'pkginfo/examples/array-argument'>;
}
declare module 'pkginfo/examples/multiple-properties.js' {
  declare module.exports: $Exports<'pkginfo/examples/multiple-properties'>;
}
declare module 'pkginfo/examples/object-argument.js' {
  declare module.exports: $Exports<'pkginfo/examples/object-argument'>;
}
declare module 'pkginfo/examples/single-property.js' {
  declare module.exports: $Exports<'pkginfo/examples/single-property'>;
}
declare module 'pkginfo/examples/target-dir.js' {
  declare module.exports: $Exports<'pkginfo/examples/target-dir'>;
}
declare module 'pkginfo/lib/pkginfo.js' {
  declare module.exports: $Exports<'pkginfo/lib/pkginfo'>;
}
declare module 'pkginfo/test/pkginfo-test.js' {
  declare module.exports: $Exports<'pkginfo/test/pkginfo-test'>;
}
