// flow-typed signature: 269daa88cf96222ec337ad11f33aeff0
// flow-typed version: <<STUB>>/polished_v2.3.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polished'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polished' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polished/babel.config' {
  declare module.exports: any;
}

declare module 'polished/dist/polished.es' {
  declare module.exports: any;
}

declare module 'polished/dist/polished' {
  declare module.exports: any;
}

declare module 'polished/dist/polished.min' {
  declare module.exports: any;
}

declare module 'polished/docs/assets/anchor' {
  declare module.exports: any;
}

declare module 'polished/docs/assets/docs' {
  declare module.exports: any;
}

declare module 'polished/docs/assets/highlight.pack' {
  declare module.exports: any;
}

declare module 'polished/docs/assets/polished' {
  declare module.exports: any;
}

declare module 'polished/docs/assets/script' {
  declare module.exports: any;
}

declare module 'polished/lib/color/adjustHue' {
  declare module.exports: any;
}

declare module 'polished/lib/color/complement' {
  declare module.exports: any;
}

declare module 'polished/lib/color/darken' {
  declare module.exports: any;
}

declare module 'polished/lib/color/desaturate' {
  declare module.exports: any;
}

declare module 'polished/lib/color/getLuminance' {
  declare module.exports: any;
}

declare module 'polished/lib/color/grayscale' {
  declare module.exports: any;
}

declare module 'polished/lib/color/hsl' {
  declare module.exports: any;
}

declare module 'polished/lib/color/hsla' {
  declare module.exports: any;
}

declare module 'polished/lib/color/invert' {
  declare module.exports: any;
}

declare module 'polished/lib/color/lighten' {
  declare module.exports: any;
}

declare module 'polished/lib/color/mix' {
  declare module.exports: any;
}

declare module 'polished/lib/color/opacify' {
  declare module.exports: any;
}

declare module 'polished/lib/color/parseToHsl' {
  declare module.exports: any;
}

declare module 'polished/lib/color/parseToRgb' {
  declare module.exports: any;
}

declare module 'polished/lib/color/readableColor' {
  declare module.exports: any;
}

declare module 'polished/lib/color/rgb' {
  declare module.exports: any;
}

declare module 'polished/lib/color/rgba' {
  declare module.exports: any;
}

declare module 'polished/lib/color/saturate' {
  declare module.exports: any;
}

declare module 'polished/lib/color/setHue' {
  declare module.exports: any;
}

declare module 'polished/lib/color/setLightness' {
  declare module.exports: any;
}

declare module 'polished/lib/color/setSaturation' {
  declare module.exports: any;
}

declare module 'polished/lib/color/shade' {
  declare module.exports: any;
}

declare module 'polished/lib/color/tint' {
  declare module.exports: any;
}

declare module 'polished/lib/color/toColorString' {
  declare module.exports: any;
}

declare module 'polished/lib/color/transparentize' {
  declare module.exports: any;
}

declare module 'polished/lib/helpers/directionalProperty' {
  declare module.exports: any;
}

declare module 'polished/lib/helpers/em' {
  declare module.exports: any;
}

declare module 'polished/lib/helpers/getValueAndUnit' {
  declare module.exports: any;
}

declare module 'polished/lib/helpers/modularScale' {
  declare module.exports: any;
}

declare module 'polished/lib/helpers/rem' {
  declare module.exports: any;
}

declare module 'polished/lib/helpers/stripUnit' {
  declare module.exports: any;
}

declare module 'polished/lib/index' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_capitalizeString' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_curry' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_endsWith' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_guard' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_hslToHex' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_hslToRgb' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_nameToHex' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_numberToHex' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_pxto' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_reduceHexValue' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_rgbToHsl' {
  declare module.exports: any;
}

declare module 'polished/lib/internalHelpers/_statefulSelectors' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/between' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/clearFix' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/cover' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/ellipsis' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/fluidRange' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/fontFace' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/hideText' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/hideVisually' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/hiDPI' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/normalize' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/placeholder' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/radialGradient' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/retinaImage' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/selection' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/timingFunctions' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/triangle' {
  declare module.exports: any;
}

declare module 'polished/lib/mixins/wordWrap' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/animation' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/backgroundImages' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/backgrounds' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/border' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/borderColor' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/borderRadius' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/borderStyle' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/borderWidth' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/buttons' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/margin' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/padding' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/position' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/size' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/textInputs' {
  declare module.exports: any;
}

declare module 'polished/lib/shorthands/transitions' {
  declare module.exports: any;
}

declare module 'polished/lib/types/color' {
  declare module.exports: any;
}

declare module 'polished/lib/types/fluidRangeConfiguration' {
  declare module.exports: any;
}

declare module 'polished/lib/types/fontFaceConfiguration' {
  declare module.exports: any;
}

declare module 'polished/lib/types/interactionState' {
  declare module.exports: any;
}

declare module 'polished/lib/types/modularScaleRatio' {
  declare module.exports: any;
}

declare module 'polished/lib/types/radialGradientConfiguration' {
  declare module.exports: any;
}

declare module 'polished/lib/types/sideKeyword' {
  declare module.exports: any;
}

declare module 'polished/lib/types/style' {
  declare module.exports: any;
}

declare module 'polished/lib/types/timingFunction' {
  declare module.exports: any;
}

declare module 'polished/lib/types/triangleConfiguration' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polished/babel.config.js' {
  declare module.exports: $Exports<'polished/babel.config'>;
}
declare module 'polished/dist/polished.es.js' {
  declare module.exports: $Exports<'polished/dist/polished.es'>;
}
declare module 'polished/dist/polished.js' {
  declare module.exports: $Exports<'polished/dist/polished'>;
}
declare module 'polished/dist/polished.min.js' {
  declare module.exports: $Exports<'polished/dist/polished.min'>;
}
declare module 'polished/docs/assets/anchor.js' {
  declare module.exports: $Exports<'polished/docs/assets/anchor'>;
}
declare module 'polished/docs/assets/docs.js' {
  declare module.exports: $Exports<'polished/docs/assets/docs'>;
}
declare module 'polished/docs/assets/highlight.pack.js' {
  declare module.exports: $Exports<'polished/docs/assets/highlight.pack'>;
}
declare module 'polished/docs/assets/polished.js' {
  declare module.exports: $Exports<'polished/docs/assets/polished'>;
}
declare module 'polished/docs/assets/script.js' {
  declare module.exports: $Exports<'polished/docs/assets/script'>;
}
declare module 'polished/lib/color/adjustHue.js' {
  declare module.exports: $Exports<'polished/lib/color/adjustHue'>;
}
declare module 'polished/lib/color/complement.js' {
  declare module.exports: $Exports<'polished/lib/color/complement'>;
}
declare module 'polished/lib/color/darken.js' {
  declare module.exports: $Exports<'polished/lib/color/darken'>;
}
declare module 'polished/lib/color/desaturate.js' {
  declare module.exports: $Exports<'polished/lib/color/desaturate'>;
}
declare module 'polished/lib/color/getLuminance.js' {
  declare module.exports: $Exports<'polished/lib/color/getLuminance'>;
}
declare module 'polished/lib/color/grayscale.js' {
  declare module.exports: $Exports<'polished/lib/color/grayscale'>;
}
declare module 'polished/lib/color/hsl.js' {
  declare module.exports: $Exports<'polished/lib/color/hsl'>;
}
declare module 'polished/lib/color/hsla.js' {
  declare module.exports: $Exports<'polished/lib/color/hsla'>;
}
declare module 'polished/lib/color/invert.js' {
  declare module.exports: $Exports<'polished/lib/color/invert'>;
}
declare module 'polished/lib/color/lighten.js' {
  declare module.exports: $Exports<'polished/lib/color/lighten'>;
}
declare module 'polished/lib/color/mix.js' {
  declare module.exports: $Exports<'polished/lib/color/mix'>;
}
declare module 'polished/lib/color/opacify.js' {
  declare module.exports: $Exports<'polished/lib/color/opacify'>;
}
declare module 'polished/lib/color/parseToHsl.js' {
  declare module.exports: $Exports<'polished/lib/color/parseToHsl'>;
}
declare module 'polished/lib/color/parseToRgb.js' {
  declare module.exports: $Exports<'polished/lib/color/parseToRgb'>;
}
declare module 'polished/lib/color/readableColor.js' {
  declare module.exports: $Exports<'polished/lib/color/readableColor'>;
}
declare module 'polished/lib/color/rgb.js' {
  declare module.exports: $Exports<'polished/lib/color/rgb'>;
}
declare module 'polished/lib/color/rgba.js' {
  declare module.exports: $Exports<'polished/lib/color/rgba'>;
}
declare module 'polished/lib/color/saturate.js' {
  declare module.exports: $Exports<'polished/lib/color/saturate'>;
}
declare module 'polished/lib/color/setHue.js' {
  declare module.exports: $Exports<'polished/lib/color/setHue'>;
}
declare module 'polished/lib/color/setLightness.js' {
  declare module.exports: $Exports<'polished/lib/color/setLightness'>;
}
declare module 'polished/lib/color/setSaturation.js' {
  declare module.exports: $Exports<'polished/lib/color/setSaturation'>;
}
declare module 'polished/lib/color/shade.js' {
  declare module.exports: $Exports<'polished/lib/color/shade'>;
}
declare module 'polished/lib/color/tint.js' {
  declare module.exports: $Exports<'polished/lib/color/tint'>;
}
declare module 'polished/lib/color/toColorString.js' {
  declare module.exports: $Exports<'polished/lib/color/toColorString'>;
}
declare module 'polished/lib/color/transparentize.js' {
  declare module.exports: $Exports<'polished/lib/color/transparentize'>;
}
declare module 'polished/lib/helpers/directionalProperty.js' {
  declare module.exports: $Exports<'polished/lib/helpers/directionalProperty'>;
}
declare module 'polished/lib/helpers/em.js' {
  declare module.exports: $Exports<'polished/lib/helpers/em'>;
}
declare module 'polished/lib/helpers/getValueAndUnit.js' {
  declare module.exports: $Exports<'polished/lib/helpers/getValueAndUnit'>;
}
declare module 'polished/lib/helpers/modularScale.js' {
  declare module.exports: $Exports<'polished/lib/helpers/modularScale'>;
}
declare module 'polished/lib/helpers/rem.js' {
  declare module.exports: $Exports<'polished/lib/helpers/rem'>;
}
declare module 'polished/lib/helpers/stripUnit.js' {
  declare module.exports: $Exports<'polished/lib/helpers/stripUnit'>;
}
declare module 'polished/lib/index.js' {
  declare module.exports: $Exports<'polished/lib/index'>;
}
declare module 'polished/lib/internalHelpers/_capitalizeString.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_capitalizeString'>;
}
declare module 'polished/lib/internalHelpers/_curry.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_curry'>;
}
declare module 'polished/lib/internalHelpers/_endsWith.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_endsWith'>;
}
declare module 'polished/lib/internalHelpers/_guard.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_guard'>;
}
declare module 'polished/lib/internalHelpers/_hslToHex.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_hslToHex'>;
}
declare module 'polished/lib/internalHelpers/_hslToRgb.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_hslToRgb'>;
}
declare module 'polished/lib/internalHelpers/_nameToHex.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_nameToHex'>;
}
declare module 'polished/lib/internalHelpers/_numberToHex.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_numberToHex'>;
}
declare module 'polished/lib/internalHelpers/_pxto.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_pxto'>;
}
declare module 'polished/lib/internalHelpers/_reduceHexValue.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_reduceHexValue'>;
}
declare module 'polished/lib/internalHelpers/_rgbToHsl.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_rgbToHsl'>;
}
declare module 'polished/lib/internalHelpers/_statefulSelectors.js' {
  declare module.exports: $Exports<'polished/lib/internalHelpers/_statefulSelectors'>;
}
declare module 'polished/lib/mixins/between.js' {
  declare module.exports: $Exports<'polished/lib/mixins/between'>;
}
declare module 'polished/lib/mixins/clearFix.js' {
  declare module.exports: $Exports<'polished/lib/mixins/clearFix'>;
}
declare module 'polished/lib/mixins/cover.js' {
  declare module.exports: $Exports<'polished/lib/mixins/cover'>;
}
declare module 'polished/lib/mixins/ellipsis.js' {
  declare module.exports: $Exports<'polished/lib/mixins/ellipsis'>;
}
declare module 'polished/lib/mixins/fluidRange.js' {
  declare module.exports: $Exports<'polished/lib/mixins/fluidRange'>;
}
declare module 'polished/lib/mixins/fontFace.js' {
  declare module.exports: $Exports<'polished/lib/mixins/fontFace'>;
}
declare module 'polished/lib/mixins/hideText.js' {
  declare module.exports: $Exports<'polished/lib/mixins/hideText'>;
}
declare module 'polished/lib/mixins/hideVisually.js' {
  declare module.exports: $Exports<'polished/lib/mixins/hideVisually'>;
}
declare module 'polished/lib/mixins/hiDPI.js' {
  declare module.exports: $Exports<'polished/lib/mixins/hiDPI'>;
}
declare module 'polished/lib/mixins/normalize.js' {
  declare module.exports: $Exports<'polished/lib/mixins/normalize'>;
}
declare module 'polished/lib/mixins/placeholder.js' {
  declare module.exports: $Exports<'polished/lib/mixins/placeholder'>;
}
declare module 'polished/lib/mixins/radialGradient.js' {
  declare module.exports: $Exports<'polished/lib/mixins/radialGradient'>;
}
declare module 'polished/lib/mixins/retinaImage.js' {
  declare module.exports: $Exports<'polished/lib/mixins/retinaImage'>;
}
declare module 'polished/lib/mixins/selection.js' {
  declare module.exports: $Exports<'polished/lib/mixins/selection'>;
}
declare module 'polished/lib/mixins/timingFunctions.js' {
  declare module.exports: $Exports<'polished/lib/mixins/timingFunctions'>;
}
declare module 'polished/lib/mixins/triangle.js' {
  declare module.exports: $Exports<'polished/lib/mixins/triangle'>;
}
declare module 'polished/lib/mixins/wordWrap.js' {
  declare module.exports: $Exports<'polished/lib/mixins/wordWrap'>;
}
declare module 'polished/lib/shorthands/animation.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/animation'>;
}
declare module 'polished/lib/shorthands/backgroundImages.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/backgroundImages'>;
}
declare module 'polished/lib/shorthands/backgrounds.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/backgrounds'>;
}
declare module 'polished/lib/shorthands/border.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/border'>;
}
declare module 'polished/lib/shorthands/borderColor.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/borderColor'>;
}
declare module 'polished/lib/shorthands/borderRadius.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/borderRadius'>;
}
declare module 'polished/lib/shorthands/borderStyle.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/borderStyle'>;
}
declare module 'polished/lib/shorthands/borderWidth.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/borderWidth'>;
}
declare module 'polished/lib/shorthands/buttons.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/buttons'>;
}
declare module 'polished/lib/shorthands/margin.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/margin'>;
}
declare module 'polished/lib/shorthands/padding.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/padding'>;
}
declare module 'polished/lib/shorthands/position.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/position'>;
}
declare module 'polished/lib/shorthands/size.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/size'>;
}
declare module 'polished/lib/shorthands/textInputs.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/textInputs'>;
}
declare module 'polished/lib/shorthands/transitions.js' {
  declare module.exports: $Exports<'polished/lib/shorthands/transitions'>;
}
declare module 'polished/lib/types/color.js' {
  declare module.exports: $Exports<'polished/lib/types/color'>;
}
declare module 'polished/lib/types/fluidRangeConfiguration.js' {
  declare module.exports: $Exports<'polished/lib/types/fluidRangeConfiguration'>;
}
declare module 'polished/lib/types/fontFaceConfiguration.js' {
  declare module.exports: $Exports<'polished/lib/types/fontFaceConfiguration'>;
}
declare module 'polished/lib/types/interactionState.js' {
  declare module.exports: $Exports<'polished/lib/types/interactionState'>;
}
declare module 'polished/lib/types/modularScaleRatio.js' {
  declare module.exports: $Exports<'polished/lib/types/modularScaleRatio'>;
}
declare module 'polished/lib/types/radialGradientConfiguration.js' {
  declare module.exports: $Exports<'polished/lib/types/radialGradientConfiguration'>;
}
declare module 'polished/lib/types/sideKeyword.js' {
  declare module.exports: $Exports<'polished/lib/types/sideKeyword'>;
}
declare module 'polished/lib/types/style.js' {
  declare module.exports: $Exports<'polished/lib/types/style'>;
}
declare module 'polished/lib/types/timingFunction.js' {
  declare module.exports: $Exports<'polished/lib/types/timingFunction'>;
}
declare module 'polished/lib/types/triangleConfiguration.js' {
  declare module.exports: $Exports<'polished/lib/types/triangleConfiguration'>;
}
