// flow-typed signature: 4fb3dfe55b5d1711432e74df5fa80adc
// flow-typed version: <<STUB>>/react-router_v4.3.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/es/generatePath' {
  declare module.exports: any;
}

declare module 'react-router/es/index' {
  declare module.exports: any;
}

declare module 'react-router/es/matchPath' {
  declare module.exports: any;
}

declare module 'react-router/es/MemoryRouter' {
  declare module.exports: any;
}

declare module 'react-router/es/Prompt' {
  declare module.exports: any;
}

declare module 'react-router/es/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/es/Route' {
  declare module.exports: any;
}

declare module 'react-router/es/Router' {
  declare module.exports: any;
}

declare module 'react-router/es/RouterContext' {
  declare module.exports: any;
}

declare module 'react-router/es/StaticRouter' {
  declare module.exports: any;
}

declare module 'react-router/es/Switch' {
  declare module.exports: any;
}

declare module 'react-router/es/withRouter' {
  declare module.exports: any;
}

declare module 'react-router/generatePath' {
  declare module.exports: any;
}

declare module 'react-router/matchPath' {
  declare module.exports: any;
}

declare module 'react-router/MemoryRouter' {
  declare module.exports: any;
}

declare module 'react-router/Prompt' {
  declare module.exports: any;
}

declare module 'react-router/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/Route' {
  declare module.exports: any;
}

declare module 'react-router/Router' {
  declare module.exports: any;
}

declare module 'react-router/StaticRouter' {
  declare module.exports: any;
}

declare module 'react-router/Switch' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router.min' {
  declare module.exports: any;
}

declare module 'react-router/withRouter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/es/generatePath.js' {
  declare module.exports: $Exports<'react-router/es/generatePath'>;
}
declare module 'react-router/es/index.js' {
  declare module.exports: $Exports<'react-router/es/index'>;
}
declare module 'react-router/es/matchPath.js' {
  declare module.exports: $Exports<'react-router/es/matchPath'>;
}
declare module 'react-router/es/MemoryRouter.js' {
  declare module.exports: $Exports<'react-router/es/MemoryRouter'>;
}
declare module 'react-router/es/Prompt.js' {
  declare module.exports: $Exports<'react-router/es/Prompt'>;
}
declare module 'react-router/es/Redirect.js' {
  declare module.exports: $Exports<'react-router/es/Redirect'>;
}
declare module 'react-router/es/Route.js' {
  declare module.exports: $Exports<'react-router/es/Route'>;
}
declare module 'react-router/es/Router.js' {
  declare module.exports: $Exports<'react-router/es/Router'>;
}
declare module 'react-router/es/RouterContext.js' {
  declare module.exports: $Exports<'react-router/es/RouterContext'>;
}
declare module 'react-router/es/StaticRouter.js' {
  declare module.exports: $Exports<'react-router/es/StaticRouter'>;
}
declare module 'react-router/es/Switch.js' {
  declare module.exports: $Exports<'react-router/es/Switch'>;
}
declare module 'react-router/es/withRouter.js' {
  declare module.exports: $Exports<'react-router/es/withRouter'>;
}
declare module 'react-router/generatePath.js' {
  declare module.exports: $Exports<'react-router/generatePath'>;
}
declare module 'react-router/index' {
  declare module.exports: $Exports<'react-router'>;
}
declare module 'react-router/index.js' {
  declare module.exports: $Exports<'react-router'>;
}
declare module 'react-router/matchPath.js' {
  declare module.exports: $Exports<'react-router/matchPath'>;
}
declare module 'react-router/MemoryRouter.js' {
  declare module.exports: $Exports<'react-router/MemoryRouter'>;
}
declare module 'react-router/Prompt.js' {
  declare module.exports: $Exports<'react-router/Prompt'>;
}
declare module 'react-router/Redirect.js' {
  declare module.exports: $Exports<'react-router/Redirect'>;
}
declare module 'react-router/Route.js' {
  declare module.exports: $Exports<'react-router/Route'>;
}
declare module 'react-router/Router.js' {
  declare module.exports: $Exports<'react-router/Router'>;
}
declare module 'react-router/StaticRouter.js' {
  declare module.exports: $Exports<'react-router/StaticRouter'>;
}
declare module 'react-router/Switch.js' {
  declare module.exports: $Exports<'react-router/Switch'>;
}
declare module 'react-router/umd/react-router.js' {
  declare module.exports: $Exports<'react-router/umd/react-router'>;
}
declare module 'react-router/umd/react-router.min.js' {
  declare module.exports: $Exports<'react-router/umd/react-router.min'>;
}
declare module 'react-router/withRouter.js' {
  declare module.exports: $Exports<'react-router/withRouter'>;
}
