// flow-typed signature: 844045a071365b8f4e9d7d1aac302959
// flow-typed version: <<STUB>>/react-autosuggest_v9.4.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-autosuggest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-autosuggest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-autosuggest/dist/Autosuggest' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/index' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/standalone/autosuggest' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/standalone/autosuggest.min' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/theme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-autosuggest/dist/Autosuggest.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/Autosuggest'>;
}
declare module 'react-autosuggest/dist/index.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/index'>;
}
declare module 'react-autosuggest/dist/standalone/autosuggest.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/standalone/autosuggest'>;
}
declare module 'react-autosuggest/dist/standalone/autosuggest.min.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/standalone/autosuggest.min'>;
}
declare module 'react-autosuggest/dist/theme.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/theme'>;
}
