import { beforeAll, describe, expect, test } from 'vitest';

import { Config, getDefaultConfig } from '@verdaccio/config';
import { logger, setup } from '@verdaccio/logger';
import type { DistFile } from '@verdaccio/types';

import { Storage } from '../src';

/**
 * getUpLinkForDistFile is private; it only touches `uplinks`, `config` and
 * `logger`, so it is exercised against a minimal fake instance instead of a
 * fully initialized Storage.
 */
function select(uplinks: Record<string, any>, packages: any, pkgName: string, distFile: DistFile) {
  const config = new Config({ ...getDefaultConfig(), packages } as any);
  const self = { uplinks, config, logger };
  return (Storage.prototype as any).getUpLinkForDistFile.call(self, pkgName, distFile);
}

function fakeUplink(name: string, url: string): any {
  return { uplinkName: name, url: new URL(url), config: { url } };
}

const openAccess = (proxy: string[]) => ({
  '**': { access: ['$all'], publish: ['$all'], proxy },
});

beforeAll(async () => {
  await setup({});
});

describe('getUpLinkForDistFile', () => {
  test('picks the uplink that serves the distfile url, not the last match', () => {
    const uplinks = {
      npmjs: fakeUplink('npmjs', 'https://registry.npmjs.org/'),
      company: fakeUplink('company', 'https://npm.company.test/'),
    };
    const distFile: DistFile = {
      url: 'https://registry.npmjs.org/pkg/-/pkg-1.0.0.tgz',
      sha: 'x',
    };

    const picked = select(uplinks, openAccess(['npmjs', 'company']), 'pkg', distFile);
    expect(picked.uplinkName).toBe('npmjs');
  });

  test('the last configured uplink keeps winning among duplicated urls', () => {
    const uplinks = {
      first: fakeUplink('first', 'https://registry.npmjs.org/'),
      second: fakeUplink('second', 'https://registry.npmjs.org/'),
    };
    const distFile: DistFile = {
      url: 'https://registry.npmjs.org/pkg/-/pkg-1.0.0.tgz',
      sha: 'x',
    };

    const picked = select(uplinks, openAccess(['first', 'second']), 'pkg', distFile);
    expect(picked.uplinkName).toBe('second');
  });

  test('a recorded registry wins over url matching', () => {
    const uplinks = {
      npmjs: fakeUplink('npmjs', 'https://registry.npmjs.org/'),
      mirror: fakeUplink('mirror', 'https://registry.npmjs.org/'),
    };
    const distFile: DistFile = {
      url: 'https://registry.npmjs.org/pkg/-/pkg-1.0.0.tgz',
      sha: 'x',
      registry: 'npmjs',
    };

    const picked = select(uplinks, openAccess(['npmjs', 'mirror']), 'pkg', distFile);
    expect(picked.uplinkName).toBe('npmjs');
  });

  test('a single configured uplink keeps serving CDN-hosted tarballs', () => {
    const uplinks = {
      github: fakeUplink('github', 'https://npm.pkg.github.com/'),
    };
    const distFile: DistFile = {
      url: 'https://cdn.example.com/tarballs/pkg-1.0.0.tgz',
      sha: 'x',
    };

    const picked = select(uplinks, openAccess(['github']), 'pkg', distFile);
    expect(picked.uplinkName).toBe('github');
  });

  test('several candidates and no url match fall back to an autogenerated proxy', () => {
    const uplinks = {
      npmjs: fakeUplink('npmjs', 'https://registry.npmjs.org/'),
      company: fakeUplink('company', 'https://npm.company.test/'),
    };
    const distFile: DistFile = {
      url: 'https://somewhere-else.test/pkg/-/pkg-1.0.0.tgz',
      sha: 'x',
    };

    const picked = select(uplinks, openAccess(['npmjs', 'company']), 'pkg', distFile);
    // no configured uplink (and none of their credentials) is reused
    expect(picked.uplinkName).toBe('verdaccio-pkg');
  });
});
