import { beforeAll, describe, expect, test } from 'vitest';

import { Config, getDefaultConfig } from '@verdaccio/config';
import { logger, setup } from '@verdaccio/logger';
import type { DistFile } from '@verdaccio/types';

import { Storage } from '../src';

/**
 * getUpLinkForDistFile is private; it only touches `uplinks`, `config` and
 * `logger`, so it is exercised against a minimal fake instance instead of a
 * fully initialized Storage.
 */
function select(
  uplinks: Record<string, any>,
  packages: any,
  pkgName: string,
  filename: string,
  distFile: DistFile,
  origin?: any
) {
  const config = new Config({ ...getDefaultConfig(), packages } as any);
  const self = { uplinks, config, logger };
  return (Storage.prototype as any).getUpLinkForDistFile.call(
    self,
    pkgName,
    filename,
    distFile,
    origin
  );
}

// an uplink-synced package records the tarball under `_distfiles`; a locally
// published one only has versions[].dist.tarball, so `_distfiles` is empty
const syncedOrigin = (filename: string, distFile: DistFile) => ({
  _distfiles: { [filename]: distFile },
});

function fakeUplink(name: string, url: string): any {
  return { uplinkName: name, url: new URL(url), config: { url } };
}

const openAccess = (proxy: string[]) => ({
  '**': { access: ['$all'], publish: ['$all'], proxy },
});

beforeAll(async () => {
  await setup({});
});

describe('getUpLinkForDistFile', () => {
  test('picks the uplink that serves the distfile url, not the last match', () => {
    const uplinks = {
      npmjs: fakeUplink('npmjs', 'https://registry.npmjs.org/'),
      company: fakeUplink('company', 'https://npm.company.test/'),
    };
    const distFile: DistFile = {
      url: 'https://registry.npmjs.org/pkg/-/pkg-1.0.0.tgz',
      sha: 'x',
    };

    const picked = select(
      uplinks,
      openAccess(['npmjs', 'company']),
      'pkg',
      'pkg-1.0.0.tgz',
      distFile
    );
    expect(picked.uplinkName).toBe('npmjs');
  });

  test('the last configured uplink keeps winning among duplicated urls', () => {
    const uplinks = {
      first: fakeUplink('first', 'https://registry.npmjs.org/'),
      second: fakeUplink('second', 'https://registry.npmjs.org/'),
    };
    const distFile: DistFile = {
      url: 'https://registry.npmjs.org/pkg/-/pkg-1.0.0.tgz',
      sha: 'x',
    };

    const picked = select(
      uplinks,
      openAccess(['first', 'second']),
      'pkg',
      'pkg-1.0.0.tgz',
      distFile
    );
    expect(picked.uplinkName).toBe('second');
  });

  test('a recorded registry wins over url matching', () => {
    const uplinks = {
      npmjs: fakeUplink('npmjs', 'https://registry.npmjs.org/'),
      mirror: fakeUplink('mirror', 'https://registry.npmjs.org/'),
    };
    const distFile: DistFile = {
      url: 'https://registry.npmjs.org/pkg/-/pkg-1.0.0.tgz',
      sha: 'x',
      registry: 'npmjs',
    };

    const picked = select(
      uplinks,
      openAccess(['npmjs', 'mirror']),
      'pkg',
      'pkg-1.0.0.tgz',
      distFile
    );
    expect(picked.uplinkName).toBe('npmjs');
  });

  test('a recorded registry is ignored when it does not serve the url', () => {
    const uplinks = {
      npmjs: fakeUplink('npmjs', 'https://registry.npmjs.org/'),
    };
    const distFile: DistFile = {
      url: 'https://cdn.example.com/tarballs/pkg-1.0.0.tgz',
      sha: 'x',
      registry: 'npmjs',
    };

    // recorded uplink does not serve the CDN url, and the package is synced,
    // so a credential-less proxy is used instead of npmjs' Authorization
    const picked = select(
      uplinks,
      openAccess(['npmjs']),
      'pkg',
      'pkg-1.0.0.tgz',
      distFile,
      syncedOrigin('pkg-1.0.0.tgz', distFile)
    );
    expect(picked.uplinkName).toBe('verdaccio-pkg');
  });

  test('a single uplink no longer lends its credentials to a CDN tarball', () => {
    const uplinks = {
      github: fakeUplink('github', 'https://npm.pkg.github.com/'),
    };
    const distFile: DistFile = {
      url: 'https://cdn.example.com/tarballs/pkg-1.0.0.tgz',
      sha: 'x',
    };

    // synced package: the CDN tarball still downloads, but via an
    // autogenerated proxy without the uplink's Authorization
    const picked = select(
      uplinks,
      openAccess(['github']),
      'pkg',
      'pkg-1.0.0.tgz',
      distFile,
      syncedOrigin('pkg-1.0.0.tgz', distFile)
    );
    expect(picked.uplinkName).toBe('verdaccio-pkg');
  });

  test('an off-uplink tarball on a locally published package is refused', () => {
    const uplinks = {
      npmjs: fakeUplink('npmjs', 'https://registry.npmjs.org/'),
    };
    const distFile: DistFile = {
      url: 'https://internal-ssrf.test/SECRET/pkg-1.0.0.tgz',
      sha: 'x',
    };

    // no `_distfiles` record → client-controlled url → do not fetch
    const picked = select(uplinks, openAccess(['npmjs']), 'pkg', 'pkg-1.0.0.tgz', distFile, {
      _distfiles: {},
    });
    expect(picked).toBeNull();
  });

  test('several candidates and no url match fall back to an autogenerated proxy for synced packages', () => {
    const uplinks = {
      npmjs: fakeUplink('npmjs', 'https://registry.npmjs.org/'),
      company: fakeUplink('company', 'https://npm.company.test/'),
    };
    const distFile: DistFile = {
      url: 'https://somewhere-else.test/pkg/-/pkg-1.0.0.tgz',
      sha: 'x',
    };

    const picked = select(
      uplinks,
      openAccess(['npmjs', 'company']),
      'pkg',
      'pkg-1.0.0.tgz',
      distFile,
      syncedOrigin('pkg-1.0.0.tgz', distFile)
    );
    // no configured uplink (and none of their credentials) is reused
    expect(picked.uplinkName).toBe('verdaccio-pkg');
  });
});
