name: Bug Report 🐛
description: A feature is not working as is expected, I want to report a bug.
title: "[Bug]: "
labels: ["bug", "issue_needs_triage"]
assignees:
  - verdacciobot
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Please do not attach files. won't be considered, drag and drop screenshots and formatted text.
      placeholder: Tell us what you see!      
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 6.x (Stable)
        - 8.x (Next)
      default: 0
    validations:
      required: true
  - type: input
    id: specificversion
    attributes:
      label: Version details
      description: Please provide the exact version number (e.g., 6.10.0)
      placeholder: ex. 6.x.x
    validations:
      required: true
  - type: textarea
    id: serverinfo
    attributes:
      label: Output server log info
      description: Add here any relevant server log output related to the issue. This will be automatically formatted into code, so no need for backticks. . Avoid sharing sensitive information.
      render: shell
      placeholder: Paste output here
    validations:
      required: false
  - type: dropdown
    id: nodeversion
    attributes:
      label: Node.js Version
      description: What Node.js version are you using?
      options:
        - 18.x.x (Latest supported)
        - 20.x.x (Maintenance)
        - 22.x.x (Maintenance)
        - 24.x.x (LTS)
        - 25.x.x (Current)
        - Other (please specify at the end of this form)
      default: 0
    validations:
      required: true      
  - type: dropdown
    id: pkgmanager
    attributes:
      label: Package manager
      description: Which package manager are you using?
      options:
        - npm
        - pnpm
        - yarn
        - Other (please specify at the end of this form)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: What operating system are you using?
      options:
        - mac
        - windows
        - linux
        - Other (please specify at the end of this form)
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: reverseproxy
    attributes:
      label: Using reverse proxy
      description: Are you using a reverse proxy (e.g., nginx, apache)?
      options:
        - label: I am using a reverse proxy
          required: false    
  # - type: dropdown
  #   id: container
  #   attributes:
  #     label: Container
  #     description: What container runtime are you using?
  #     options:
  #       - none
  #       - docker
  #       - helm
  #       - kubernetes
  #     default: 0
  #   validations:
  #     required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. Avoid sharing sensitive information.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Have I checked other issues?
      description: Before submitting this issue, I have searched for existing issues that may be related to my problem.
      options:
        - label: I have searched existing issues
          required: true
