blank_issues_enabled: false
contact_links:
  - name: Documentation 📚
    url: https://verdaccio.org/docs/installation
    about: Find more information in our documentation resources
  - name: Feature Request 🌟
    url: https://github.com/orgs/verdaccio/discussions/new?category=ideas
    about: 🆕 Open a new feature request discussion 🙏
  - name: Question 🤷🏻‍♂️
    url: https://github.com/verdaccio/verdaccio/discussions/new?category=q-a
    about: 🆕 Open a new Q&A discussion 🙏
  - name: Chat 🏘
    url: https://discord.gg/7qWJxBf
    about: Quick question? Try out Discord chat, you can get faster feedback
