name: Feature Request ✨
description: Suggest a new feature or enhancement for Verdaccio.
title: "[Feature]: "
labels: ["topic: feature request"]
assignees:
  - verdacciobot
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the details below.
  - type: textarea
    id: feature-description
    attributes:
      label: What is the feature you'd like to see?
      description: Clearly describe the feature or enhancement you are proposing.
      placeholder: Describe your feature idea!
      value: "I would like..."
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Why is this feature needed?
      description: Explain the use case or problem this feature would solve.
      placeholder: Why do you need this feature?
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Verdaccio are you using?
      options:
        - 6.x (Stable)
        - 8.x (Experimental)
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Have I checked other issues?
      description: Before submitting this feature request, I have searched for existing issues or pull requests that may be related.
      options:
        - label: I have searched existing issues and PRs
          required: true
