#!/bin/sh

# Check if the current UID has an entry in /etc/passwd
# - `whoami` fails if the UID is not present
if ! whoami &> /dev/null; then
  # If /etc/passwd is writable, append a new user entry
  # - This makes sure the current user can be resolved
  if [ -w /etc/passwd ]; then
    echo "${VERDACCIO_USER_NAME:-default}:x:$(id -u):0:${VERDACCIO_USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi

# Hand off control to the main container process using dumb-init
# - `dumb-init` handles PID 1 responsibilities 
# - `"$@"` passes through any CMD args 
exec /usr/bin/dumb-init -- "$@"
