#!/usr/bin/env node
// Prepares the Docker build context for a Verdaccio 6.x image that uses the
// packages built from THIS repository instead of the versions published on npm.
//
// What it does:
//   1. (optionally) builds every workspace package — `SKIP_BUILD=1` to skip.
//   2. runs `pnpm pack` on each publishable @verdaccio/* (and verdaccio-*) package.
//      pnpm rewrites `workspace:*` specifiers to real versions in the tarball, so
//      the artifact is exactly what would be published to npm.
//   3. writes docker/verdaccio6x/dist/package.json declaring `verdaccio@^6` plus an
//      npm `overrides` map that forces every one of those packages — transitively —
//      to the freshly packed local tarball.
//
// The Dockerfile then runs `npm install` against that package.json, producing a
// verdaccio@6 install whose entire @verdaccio/* tree is the local build.
import { execFileSync, execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..');
const distDir = join(here, 'dist');
const tarballsDir = join(distDir, 'tarballs');

// Dev-only tooling that is never part of the verdaccio runtime tree.
const EXCLUDE = new Set(['@verdaccio/eslint-config', '@verdaccio/test-helper']);

const VERDACCIO_VERSION = process.env.VERDACCIO_VERSION || '^6';

function log(msg) {
  console.log(`[verdaccio6x] ${msg}`);
}

/** Recursively collect every package.json under packages/, skipping build artifacts. */
function findPackageJsons(dir, found = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (['node_modules', 'build', 'dist', 'coverage', 'test', '.turbo'].includes(entry.name)) {
        continue;
      }
      findPackageJsons(join(dir, entry.name), found);
    } else if (entry.name === 'package.json') {
      found.push(join(dir, entry.name));
    }
  }
  return found;
}

function collectPackages() {
  const pkgs = [];
  for (const file of findPackageJsons(join(repoRoot, 'packages'))) {
    let pkg;
    try {
      pkg = JSON.parse(readFileSync(file, 'utf8'));
    } catch {
      continue;
    }
    const name = pkg.name;
    if (!name || pkg.private) continue;
    if (!name.startsWith('@verdaccio/') && !name.startsWith('verdaccio-')) continue;
    if (EXCLUDE.has(name)) continue;
    pkgs.push({ name, version: pkg.version, dir: dirname(file) });
  }
  return pkgs.sort((a, b) => a.name.localeCompare(b.name));
}

/** Pack one package and return the tarball file name (basename). */
function pack(pkg) {
  const out = execFileSync('pnpm', ['pack', '--pack-destination', tarballsDir], {
    cwd: pkg.dir,
    encoding: 'utf8',
  });
  const tgzLine = out
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.endsWith('.tgz'))
    .pop();
  if (tgzLine) return basename(tgzLine);
  // Fallback to the deterministic npm/pnpm naming convention.
  const fallback = `${pkg.name.replace(/^@/, '').replace(/\//g, '-')}-${pkg.version}.tgz`;
  if (existsSync(join(tarballsDir, fallback))) return fallback;
  throw new Error(`could not determine tarball name for ${pkg.name}`);
}

function main() {
  log(`repo root: ${repoRoot}`);
  rmSync(distDir, { recursive: true, force: true });
  mkdirSync(tarballsDir, { recursive: true });

  if (process.env.SKIP_BUILD === '1') {
    log('SKIP_BUILD=1 — using existing build output');
  } else {
    log('building all workspace packages (set SKIP_BUILD=1 to skip)…');
    execSync('pnpm build', { cwd: repoRoot, stdio: 'inherit' });
  }

  const packages = collectPackages();
  log(`packing ${packages.length} packages…`);

  const overrides = {};
  for (const pkg of packages) {
    const file = pack(pkg);
    overrides[pkg.name] = `file:tarballs/${file}`;
    log(`  ${pkg.name}@${pkg.version} -> ${file}`);
  }

  const appPackageJson = {
    name: 'verdaccio-6x-local',
    version: '0.0.0',
    private: true,
    description: 'Verdaccio 6.x running against locally-built @verdaccio/* packages',
    dependencies: { verdaccio: VERDACCIO_VERSION },
  };
  writeFileSync(join(distDir, 'package.json'), JSON.stringify(appPackageJson, null, 2) + '\n');

  // pnpm settings live in pnpm-workspace.yaml (as in this repo) rather than .npmrc.
  // `overrides` applies transitively by package name, so every nested @verdaccio/*
  // dependency resolves to the local tarball. `nodeLinker: hoisted` gives a flat
  // node_modules so verdaccio can require every plugin like a classic install.
  const overridesYaml = Object.entries(overrides)
    .map(([name, spec]) => `  '${name}': '${spec}'`)
    .join('\n');
  const workspaceYaml =
    `# Generated by prepare.mjs — pnpm config for the verdaccio 6.x test image.\n` +
    `nodeLinker: hoisted\n` +
    `overrides:\n${overridesYaml}\n`;
  writeFileSync(join(distDir, 'pnpm-workspace.yaml'), workspaceYaml);

  log(`done. context ready at ${distDir}`);
  log(`verdaccio version: ${VERDACCIO_VERSION}, overridden packages: ${packages.length}`);
}

main();
