name: 'Cache build'
description: 'get or set cache build'

runs:
  using: composite
  steps:
    - name: Cache .pnpm-store
      id: cache-npm
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.event.pull_request.number }}-${{ runner.os }}
        restore-keys: |
          pnpm-

