name: 'Cache build'
description: 'get or set cache build'

runs:
  using: composite
  steps:
    - name: Cache .pnpm-store
      id: cache-npm
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.event.pull_request.number }}-${{ runner.os }}
        restore-keys: |
          pnpm-

