name: 'Cache build'
description: 'get or set cache build'

runs:
  using: composite
  steps:
    - name: Cache .pnpm-store
      id: cache-npm
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.event.pull_request.number }}-${{ runner.os }}
        restore-keys: |
          pnpm-

