name: 'Cache build'
description: 'get or set cache build'

runs:
  using: composite
  steps:
    - name: Cache .pnpm-store
      id: cache-npm
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.event.pull_request.number }}-${{ runner.os }}
        restore-keys: |
          pnpm-

