services:
  verdaccio:
    image: verdaccio/verdaccio:6
    container_name: verdaccio-docker-local-storage-vol
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
