name: 'Install app with Node specific version'
description: 'install application'

inputs:
  registry-url:
    description: 'Registry URL for pnpm'
    required: false
    default: 'http://localhost:4873'
  reporter:
    description: 'Reporter for pnpm'
    required: false
    default: 'silent'
  node-version:
    description: 'Node.js version to use'
    required: true

runs:
  using: composite
  steps:
    - name: Use Node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install pnpm
      run: |
        corepack enable
        corepack prepare
      shell: bash
    - name: set store
      run: |
        if [ ! -d "$HOME/.pnpm-store" ]; then
          mkdir -p $HOME/.pnpm-store
          pnpm config set store-dir $HOME/.pnpm-store
        else
          echo "Store directory already exists. Skipping configuration."
        fi
      shell: bash
    - name: Restore cache pnpm store
      uses: ./.github/actions/cache-store
    - name: Install
      run: pnpm install --reporter=${{inputs.reporter}} --ignore-scripts --registry ${{ inputs.registry-url }}
      shell: bash
    - name: Save cache pnpm store
      if: steps.cache-npm.outputs.cache-hit == 'false'
      uses: ./.github/actions/cache-store

