name: 'Install app'
description: 'install application'

inputs:
  registry-url:
    description: 'Registry URL for pnpm'
    required: false
    default: 'http://localhost:4873'
  reporter:
    description: 'Reporter for pnpm'
    required: false
    default: 'silent'

runs:
  using: composite
  steps:
    - name: Use Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: '.nvmrc'
    - name: Install pnpm
      run: |
        npm install --global corepack@latest
        corepack enable
        corepack prepare
      shell: bash
    - name: set store
      run: |
        mkdir ~/.pnpm-store
        pnpm config set store-dir ~/.pnpm-store
      shell: bash
    - name: Restore cache pnpm store
      uses: ./.github/actions/cache-store
    - name: Install
      run: pnpm install --reporter=${{inputs.reporter}} --ignore-scripts --registry ${{ inputs.registry-url }}
      shell: bash
    - name: Save cache pnpm store
      if: steps.cache-npm.outputs.cache-hit == 'false'
      uses: ./.github/actions/cache-store

