/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      href: '/contributors',
      label: 'Meet the Contributors',
    },
    {
      type: 'link',
      label: 'Watch us on YouTube',
      href: 'https://www.youtube.com/channel/UC5i20v6o7lSjXzAHOvatt0w',
    },    
    {
      type: 'link',
      label: 'Chat on Discord',
      href: 'https://discord.gg/T7gJmBM6nv',
    },
    {
      type: 'link',
      label: 'Open Collective',
      href: 'https://opencollective.com/verdaccio',
    },
    {
      type: 'link',
      label: 'GitHub Sponsors',
      href: 'https://github.com/sponsors/verdaccio',
    },
    {
      type: 'link',
      label: 'LICENSE',
      href: 'https://github.com/verdaccio/verdaccio/blob/master/LICENSE',
    },    
  ],
};
