name: E2E Docker Proxy Plugins Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    # run every sunday
    - cron: '0 0 * * 0'
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      
    - name: Start containers
      run: docker compose -f "./e2e/docker/docker-build-install-plugin/docker-compose.yaml" up -d --build

    - name: Install node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      with:
        node-version: 18

    - name: verdaccio cli
      run: npm install -g verdaccio --registry=http://localhost:4873
    - name: gastby cli 
      run:  npm install -g gatsby-cli --registry http://localhost:4873
    - name: netlify cli 
      run:  npm install -g netlify-cli --registry http://localhost:4873
    - name: angular cli 
      run:  npm install -g @angular/cli --registry http://localhost:4873

    - name: Stop containers
      if: always()
      run: docker compose -f "./e2e/docker/docker-build-install-plugin/docker-compose.yaml" down
