name: Changesets

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  # Update package versions from changesets.
  version:
    timeout-minutes: 14
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository == 'verdaccio/verdaccio'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies with a custom registry
        uses: ./.github/actions/install-app
      - name: crowdin download
        env:
          CROWDIN_VERDACCIO_API_KEY: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}
          CONTEXT: production
        run: pnpm crowdin:download
      - name: build
        run: pnpm build
      - name: create versions
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b
        with:
          version: pnpm ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
          createGithubReleases: false
          setupGitUser: true
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.REGISTRY_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_AUTH_TOKEN }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org
