name: pnpm audit

on:
  push:
  pull_request:
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/pnpm-audit.yml'
      - '.github/workflows/x-pnpm-audit.yml'

concurrency:
  group: pnpm-audit-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit:
    uses: ./.github/workflows/x-pnpm-audit.yml
