name: "Deploy with Security Checks"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  security-events: write

env:
  IMAGE_TAG: ${{ github.sha }}


jobs:
  security:
    uses: ./.github/workflows/shared-jops.yml
    with:
      deploy: true
    secrets: inherit
 
