name: Import Module Smoke Test

on: [pull_request]

permissions:
  contents: read
concurrency:
  group: smoke-test-import-module-${{ github.ref }}-6x
  cancel-in-progress: true
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node_version: [24, 25]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: Start Verdaccio Docker
        run: docker run -d -it --rm --name verdaccio -p 4873:4873 -e "DEBUG=verdaccio*" verdaccio/verdaccio:6
      - name: Login to local registry
        run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873
      - name: Install dependencies
        run: yarn
      - name: Bump version and publish
        run: |
          npm version prerelease --no-git-tag-version --preid $(date +%s%N)
          echo "VERDACCIO_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          yarn build
          npm publish --tag next --registry http://localhost:4873
      - name: Run smoke tests (ESM + CJS)
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "CI"
          VERDACCIO_VERSION=${{ env.VERDACCIO_VERSION }} REGISTRY=http://localhost:4873 ./scripts/smoke-test/run.sh
