name: Module Smoke Test

on: [push, pull_request]  

permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}-6x
  cancel-in-progress: true    
jobs:
  test:    
    strategy:
      fail-fast: false
      matrix:
        node_version: [18, 20, 22, 24]    
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2    
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:6
      - name: login    
        run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873                 
      - name: Build
        run: yarn && yarn build
      - name: Bump up package and save version
        run: |
          npm version prerelease --no-git-tag-version --preid $(date +%s%N)
          echo "VERDACCIO_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: publish verdaccio 
        run: npm publish --tag next --registry http://localhost:4873
      - name: install verdaccio 
        run: npm i -g verdaccio@${{ env.VERDACCIO_VERSION }} --loglevel info --registry http://localhost:4873
      - name: verdaccio version 
        run:  verdaccio --version
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --force
          npm install vitest --registry http://localhost:4873
          npm install verdaccio --registry http://localhost:4873
          echo "import { describe, expect, test } from 'vitest';

          test('runServer should start correctly with default config', async () => {
            const { runServer, getDefaultConfig } = require('verdaccio');
            
            expect(typeof runServer).toBe('function');            
            
            const defaultConfig = getDefaultConfig();
            console.log('Default Config:', defaultConfig);
            const server = await runServer(defaultConfig);
            
            expect(server).toBeDefined();
            expect(server).toHaveProperty('listen');
            
            if (server && typeof server.close === 'function') {
              await server.close();
            }
          });" | tee module.spec.js
          cat module.spec.js
          yarn vitest run module.spec --reporter verbose 

