on:
  workflow_call:
    inputs:
      verdaccio-version:
        description: 'Verdaccio version to use'
        required: false
        default: 'latest'
        type: string

jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Publish
      uses: verdaccio/github-actions/publish@master # always latest by design 
      with:
        args: -d
        verdaccio-version: ${{ inputs.verdaccio-version }}
