on:
  workflow_call:
    inputs:
      verdaccio-version:
        description: 'Verdaccio version to use'
        required: false
        default: 'latest'
        type: string

jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Publish
      uses: verdaccio/github-actions/publish@master # always latest by design 
      with:
        args: -d
        verdaccio-version: ${{ inputs.verdaccio-version }}
