on:
  workflow_call:

jobs:
  yarn:
    name: 'yarn:jest example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Use Node.js'
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js --config ./scripts/e2e-config.yaml &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          yarn init --yes
          yarn add jest@29.5.0 --registry http://localhost:4873

          echo "it('should pass', () => { expect(true).toBeTruthy(); });" | tee pass.test.js
          yarn jest pass.test.js

          yarn add left-pad --registry http://localhost:4873 --verbose
          echo "const leftPad = require('left-pad'); it('should resolve a module', () => { expect(typeof leftPad).toBe('function');});" | tee module.test.js
          yarn jest module.test.js
  yarn2:
    name: 'yarn2:jest example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Use Node.js'
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js --config ./scripts/e2e-config.yaml &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          yarn init --yes
          yarn set version berry
          yarn config set npmRegistryServer "http://localhost:4873"
          yarn config set unsafeHttpWhitelist --json '["localhost"]'
          yarn add jest@29.5.0

          echo "it('should pass', () => { expect(true).toBeTruthy(); });" | tee pass.test.js
          yarn jest pass.test.js

          yarn add left-pad
          echo "const leftPad = require('left-pad'); it('should resolve a module', () => { expect(typeof leftPad).toBe('function');});" | tee module.test.js
          yarn jest module.test.js
  npm8:
    name: 'npm8:jest example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Use Node.js'
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
      - name: 'install latest npm'
        run: npm i -g npm@next-8
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js  --config ./scripts/e2e-config.yaml  &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --yes
          npm install jest@29.5.0 --registry http://localhost:4873 --loglevel info

          echo "it('should pass', () => { expect(true).toBeTruthy(); });" | tee pass.test.js
          yarn jest pass.test.js

          yarn add left-pad --registry http://localhost:4873 --verbose
          echo "const leftPad = require('left-pad'); it('should resolve a module', () => { expect(typeof leftPad).toBe('function');});" | tee module.test.js
          yarn jest module.test.js
  npm9:
    name: 'npm9:jest example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Use Node.js'
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
      - name: 'install latest npm 9'
        run: npm i -g npm@next-9
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js  --config ./scripts/e2e-config.yaml  &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --yes
          npm install jest@29.4.2 --registry http://localhost:4873 --loglevel info 

          echo "it('should pass', () => { expect(true).toBeTruthy(); });" | tee pass.test.js
          yarn jest pass.test.js

          yarn add left-pad --registry http://localhost:4873 --verbose
          echo "const leftPad = require('left-pad'); it('should resolve a module', () => { expect(typeof leftPad).toBe('function');});" | tee module.test.js
          yarn jest module.test.js
  npm10:
    name: 'npm10:jest example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Use Node.js'
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
      - name: 'install latest npm 10'
        run: npm i -g npm@next-10
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js  --config ./scripts/e2e-config.yaml  &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --yes
          npm install jest@29.4.2 --registry http://localhost:4873  --loglevel info 

          echo "it('should pass', () => { expect(true).toBeTruthy(); });" | tee pass.test.js
          yarn jest pass.test.js

          yarn add left-pad --registry http://localhost:4873 --verbose
          echo "const leftPad = require('left-pad'); it('should resolve a module', () => { expect(typeof leftPad).toBe('function');});" | tee module.test.js
          yarn jest module.test.js
  pnpm8:
    name: 'pnpm8:jest example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Use Node.js'
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
      - name: 'install latest pnpm'
        run: npm i -g pnpm@latest-9
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js &
      - name: 'Ping to verdaccio'
        run: |
          pnpm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          pnpm init
          pnpm install jest@29.5.0 --registry http://localhost:4873  --loglevel info 

          echo "it('should pass', () => { expect(true).toBeTruthy(); });" | tee pass.test.js
          yarn jest pass.test.js

          yarn add left-pad --registry http://localhost:4873 --verbose
          echo "const leftPad = require('left-pad'); it('should resolve a module', () => { expect(typeof leftPad).toBe('function');});" | tee module.test.js
          yarn jest module.test.js
  pnpm9:
    name: 'pnpm:9:jest example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Use Node.js'
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
      - name: 'install latest pnpm'
        run: npm i -g pnpm@latest-9
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          yarn node ./scripts/run-verdaccio.js &
      - name: 'Ping to verdaccio'
        run: |
          pnpm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          pnpm init
          pnpm install jest@29.5.0 --registry http://localhost:4873 --loglevel info 

          echo "it('should pass', () => { expect(true).toBeTruthy(); });" | tee pass.test.js
          yarn jest pass.test.js

          yarn add left-pad --registry http://localhost:4873 --verbose
          echo "const leftPad = require('left-pad'); it('should resolve a module', () => { expect(typeof leftPad).toBe('function');});" | tee module.test.js
          yarn jest module.test.js
